### ISSUE TITLE
calling setup_gateway.sh duplicates some netfilter rules

### ISSUE THREAD

**Issue by kerlerm** [ffulm/server-config#21]
Calling the setup_gateway.sh duplicates the follwing rules with each run:

v4:
-A INPUT -i tun0 -p tcp -m tcp --dport 53 -m state --state ESTABLISHED -j ACCEPT
-A INPUT -i tun0 -p udp -m udp --dport 53 -m state --state ESTABLISHED -j ACCEPT
-A FORWARD -i nat64 -o tun0 -j ACCEPT
-A FORWARD -i tun0 -o nat64 -m state --state RELATED,ESTABLISHED -j ACCEPT

v6:
-A FORWARD -i bat0 -o nat64 -j ACCEPT
-A FORWARD -i nat64 -o bat0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i tun0 -o bat0 -m state --state RELATED,ESTABLISHED -j ACCEPT

-A POSTROUTING -o tun0 -j MASQUERADE

**Comment by kerlerm** [comment]
This is because etc/openvpn/update-route is re-adding the above rules without checking if the rules have already been set by netfilter/iptables-persistent.

**Comment by mwarning** [comment]
Using these wrappers in etc/openvpn/update-route might help:
iptables_c() { iptables $@ --check && iptables $@; }
ip6tables_c() { ip6tables $@ --check && iptables $@; }

@kerlerm: could you give it try?

**Comment by kerlerm** [comment]
https://github.com/freifunk-bielefeld/server-config/commit/debb4277fcacd53f240a2228786c6f4dcdddb84c fixes the issue. Please merge.

**Comment by mwarning** [comment]
It has been merged. :-)
